from z3 import *
general_chi = Int( 'general_chi' )
general_incidence_date = Real( 'general_incidence_date' )
general_name = String('general_name')
general_date_of_birth = Real( 'general_date_of_birth' )
general_first_seen_date = Real( 'general_first_seen_date' )
general_histology = Int( 'general_histology' )
general_metastasis1 = String('general_metastasis1')
general_metastasis2 = String('general_metastasis2')
general_metastasis3 = String('general_metastasis3')
general_cong_heart_fail_flag = Int( 'general_cong_heart_fail_flag' )
general_con_tiss_disease_rheum_flag = Int( 'general_con_tiss_disease_rheum_flag' )
general_dementia_flag = Int( 'general_dementia_flag' )
general_pulmonary_flag = Int( 'general_pulmonary_flag' )
general_con_tiss_flag = Int( 'general_con_tiss_flag' )
general_diabetes_flag = Int( 'general_diabetes_flag' )
general_para_hemiplegia_flag = Int( 'general_para_hemiplegia_flag' )
general_renal_flag = Int( 'general_renal_flag' )
general_liver_flag = Int( 'general_liver_flag' )
general_aids_hiv_flag = Int( 'general_aids_hiv_flag' )
general_charlson_score = Int( 'general_charlson_score' )
general_dob = Real( 'general_dob' )
general_age = Int( 'general_age' )
general_simd = Int( 'general_simd' )
general_simd1 = Int( 'general_simd1' )
general_side = Int( 'general_side' )
general_gender = Int( 'general_gender' )
general_age_at_diagnosis = Int( 'general_age_at_diagnosis' )
general_weight = Int( 'general_weight' )
general_bmi = Int( 'general_bmi' )
general_height = Real( 'general_height' )
general_religion = Int( 'general_religion' )
general_civil_st = Int( 'general_civil_st' )
general_ref_hospital = Int( 'general_ref_hospital' )
general_postcode_pre = String('general_postcode_pre')
general_stage = Int( 'general_stage' )
general_stage_detail = String('general_stage_detail')
general_tnm_t = Int( 'general_tnm_t' )
general_tnm_t_detail = String('general_tnm_t_detail')
general_tnm_n = Int( 'general_tnm_n' )
general_tnm_n_detail = String('general_tnm_n_detail')
general_tnm_m = Int( 'general_tnm_m' )
general_perf_stat = Int( 'general_perf_stat' )
general_smr01_flag = Int( 'general_smr01_flag' )
general_gp_name = String('general_gp_name')
general_death_flag = Int( 'general_death_flag' )
general_survival_days = Int( 'general_survival_days' )
general_gp_id = Int( 'general_gp_id' )
s = Solver()
general_chi_assigned = (general_chi == 1104833329)
general_name_assigned = (general_name == "LILLIE DOW")
s.add(general_name_assigned)
general_dob_assigned = (general_dob == 418873019497)
s.add(general_dob_assigned)
general_gender_assigned = (general_gender == 2)
s.add(general_gender_assigned)
general_chi_Distribution = (general_chi == 1073718157)
s.add(general_chi_Distribution)
general_chi_AllDiff = (general_chi != 1940320771, general_chi != 412519834)
s.add(general_chi_AllDiff)
general_incidence_date_RandomNumber= (general_incidence_date == 1471995552445)
s.add(general_incidence_date_RandomNumber)
general_date_of_birth_RandomNumber= (general_date_of_birth == -933823709107)
s.add(general_date_of_birth_RandomNumber)
general_first_seen_date_RandomNumber= (general_first_seen_date == 1596184565455)
s.add(general_first_seen_date_RandomNumber)
general_histology_WeightedDistribution = (general_histology == 8505)
s.add(general_histology_WeightedDistribution)
general_metastasis1_WeightedDistribution = (general_metastasis1 == "C00.0")
s.add(general_metastasis1_WeightedDistribution)
general_metastasis2_WeightedDistribution = (general_metastasis2 == "")
s.add(general_metastasis2_WeightedDistribution)
general_metastasis3_WeightedDistribution = (general_metastasis3 == "")
s.add(general_metastasis3_WeightedDistribution)
general_cong_heart_fail_flag_WeightedDistribution = (general_cong_heart_fail_flag == 0)
s.add(general_cong_heart_fail_flag_WeightedDistribution)
general_con_tiss_disease_rheum_flag_WeightedDistribution = (general_con_tiss_disease_rheum_flag == 0)
s.add(general_con_tiss_disease_rheum_flag_WeightedDistribution)
general_dementia_flag_WeightedDistribution = (general_dementia_flag == 0)
s.add(general_dementia_flag_WeightedDistribution)
general_pulmonary_flag_WeightedDistribution = (general_pulmonary_flag == 0)
s.add(general_pulmonary_flag_WeightedDistribution)
general_con_tiss_flag_WeightedDistribution = (general_con_tiss_flag == 0)
s.add(general_con_tiss_flag_WeightedDistribution)
general_diabetes_flag_WeightedDistribution = (general_diabetes_flag == 0)
s.add(general_diabetes_flag_WeightedDistribution)
general_para_hemiplegia_flag_WeightedDistribution = (general_para_hemiplegia_flag == 0)
s.add(general_para_hemiplegia_flag_WeightedDistribution)
general_renal_flag_WeightedDistribution = (general_renal_flag == 0)
s.add(general_renal_flag_WeightedDistribution)
general_liver_flag_WeightedDistribution = (general_liver_flag == 3)
s.add(general_liver_flag_WeightedDistribution)
general_aids_hiv_flag_WeightedDistribution = (general_aids_hiv_flag == 0)
s.add(general_aids_hiv_flag_WeightedDistribution)
general_charlson_score_WeightedDistribution = (general_charlson_score == 6)
s.add(general_charlson_score_WeightedDistribution)
general_age_WeightedDistribution = (general_age == 42)
s.add(general_age_WeightedDistribution)
general_simd_WeightedDistribution = (general_simd == 3)
s.add(general_simd_WeightedDistribution)
general_simd1_WeightedDistribution = (general_simd1 == 4)
s.add(general_simd1_WeightedDistribution)
general_side_WeightedDistribution = (general_side == 2)
s.add(general_side_WeightedDistribution)
general_age_at_diagnosis_Distribution = (general_age_at_diagnosis == 16)
s.add(general_age_at_diagnosis_Distribution)
general_weight_Distribution = (general_weight == 68)
s.add(general_weight_Distribution)
general_bmi_WeightedDistribution = (general_bmi == 22.4)
s.add(general_bmi_WeightedDistribution)
general_height_WeightedDistribution = (general_height == 1.77)
s.add(general_height_WeightedDistribution)
general_religion_WeightedDistribution = (general_religion == 9)
s.add(general_religion_WeightedDistribution)
general_civil_st_WeightedDistribution = (general_civil_st == 9)
s.add(general_civil_st_WeightedDistribution)
general_ref_hospital_WeightedDistribution = (general_ref_hospital == 410)
s.add(general_ref_hospital_WeightedDistribution)
general_postcode_pre_WeightedDistribution = (general_postcode_pre == "DG")
s.add(general_postcode_pre_WeightedDistribution)
general_stage_WeightedDistribution = (general_stage == 1)
s.add(general_stage_WeightedDistribution)
general_stage_detail_WeightedDistribution = (general_stage_detail == "1C")
s.add(general_stage_detail_WeightedDistribution)
general_tnm_t_WeightedDistribution = (general_tnm_t == 2)
s.add(general_tnm_t_WeightedDistribution)
general_tnm_t_detail_WeightedDistribution = (general_tnm_t_detail == "1")
s.add(general_tnm_t_detail_WeightedDistribution)
general_tnm_n_WeightedDistribution = (general_tnm_n == 2)
s.add(general_tnm_n_WeightedDistribution)
general_tnm_n_detail_WeightedDistribution = (general_tnm_n_detail == "0")
s.add(general_tnm_n_detail_WeightedDistribution)
general_tnm_m_WeightedDistribution = (general_tnm_m == 0)
s.add(general_tnm_m_WeightedDistribution)
general_perf_stat_WeightedDistribution = (general_perf_stat == -1)
s.add(general_perf_stat_WeightedDistribution)
general_smr01_flag_WeightedDistribution = (general_smr01_flag == 0)
s.add(general_smr01_flag_WeightedDistribution)
general_gp_name_WeightedDistribution = (general_gp_name == "MAHAR")
s.add(general_gp_name_WeightedDistribution)
general_death_flag_WeightedDistribution = (general_death_flag == 0)
s.add(general_death_flag_WeightedDistribution)
general_survival_days_WeightedDistribution = (general_survival_days == -1)
s.add(general_survival_days_WeightedDistribution)
general_gp_id_WeightedDistribution = (general_gp_id == 10)
s.add(general_gp_id_WeightedDistribution)
if s.check() == sat:
	m = s.model()
	for d in m.decls():
		print("%s = %s" % (d.name(), m[d]))
else:
	print(unsat)
	print(s.proof())
